---
name: tests
on:
  push:
    branches:
      - main
      - '*.*.*'
  pull_request:
    branches:
      - main
      - '*.*.*'

jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.12'
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Use scim2-models from repository
        run: |
          sed -i 's|scim2-models = { path = "../../", develop = true }|scim2-models = { git = "https://github.com/yaal-coop/scim2-models" }|g' pyproject.toml
          poetry lock --no-update
      - name: Install dependencies and run tests
        run: |
          poetry --version
          poetry install
          poetry run pytest --showlocals --cov --cov-fail-under=100 --cov-report term:skip-covered

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
